name: modmopet
description: A management tool for mods of Nintendo Switch emulators.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  archive: ^3.3.7
  csslib: ^0.17.0
  dio: ^5.1.2
  fast_cached_network_image: ^1.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  github: ^9.14.0
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  riverpod_annotation: ^2.1.1
  theme_tailor_annotation: ^2.0.0
  universal_html: ^2.2.2
  window_manager: ^0.3.4
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  theme_tailor: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
