name: Build & Release dev
env:
  FLUTTER_VERSION: "3.10.3"
on: workflow_dispatch
jobs:
  # build-release-windows:
  #  runs-on: windows-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: subosito/flutter-action@v2
  #      with:
  #        channel: 'stable'
  #    - run: flutter config --enable-windows-desktop
  #    - run: flutter build windows
  #    - uses: "marvinpinto/action-automatic-releases@latest"
  #      with:
  #        repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #        automatic_release_tag: "dev"
  #        prerelease: true
  #        title: "ModMopet Nightly"
  #        files: |
  #          build/macos/Build/Products/Release/Mod Mopet.app
  # build-release-linux:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: subosito/flutter-action@v2
  #      with:
  #        flutter-version: FLUTTER_VERSION
  #        channel: 'stable'
  #    - run: |
  #        sudo apt-get update -y
  #        sudo apt-get install -y ninja-build libgtk-3-dev
  #    - run: flutter config --enable-linux-desktop
  #    - run: flutter build linux
  build-release-macos:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          path: 'build/macos/Build/Products/Release'
          exclusions: '/App.*/ /FlutterMacOS/ /*.framework/*'
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "ModMopet-nightly"
          files: |
            build/macos/Build/Products/Release
